name: ColesRecipes
options:
  bundleIdPrefix: com.coles
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: "1.15.0"

targets:
  ColesRecipes:
    type: application
    platform: iOS
    sources:
      - ColesRecipes
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: true
        SWIFT_VERSION: "5.9"

  ColesRecipesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ColesRecipesTests
    dependencies:
      - target: ColesRecipes
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  ColesRecipesSnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ColesRecipesSnapshotTests
    dependencies:
      - target: ColesRecipes
      - package: SnapshotTesting
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
